### ISSUE TITLE
Multiple browser support

### ISSUE THREAD

**Issue by mpseay** [alisaifee/holmium.core#31]
Hey Hey
Holmium is awesome. I think the community would benefit a lot with a built in solution to specify an array of browser configurations per test run.

Currently, --holmium-browser is used, i'm curious is a --holmium-browsers would be possible? Either that, or specifying a list of browser configurations in the desired/holmium capabilities?

Thanks in advance guys!

**Comment by alisaifee** [comment]
Hi,
Thanks for this suggestion, I think it'll be a very useful option to have.

There are two ways I can think of providing this option:
1. run each test with the specified browsers and only mark it successful if all browsers succeed, else raise all the errors by the failing browsers. 
2. make a copy and rename each test for each browser specified (for example `TestClass.test_case_1` becomes `TestClass.test_case_1_firefox` etc..)

I've tried hacking both approaches in using `nose` but been unsuccessful so far (might need advice from the nose developers once the approach is decided on).

**Comment by alisaifee** [comment]
Closing since nose support has been dropped as of 1.0.0
