### ISSUE TITLE
Remote driver fails to initialise when used with 'ie', 'safari' as the browser

### ISSUE THREAD

**Issue by jakubkusmierz** [alisaifee/holmium.core#34]
Hello,

I am trying to run:

nosetests holmium_vistaprint_test.py -v --with-holmium --holmium-browser=ie --holmium-env=default --holmium-remote=http://my_selenium_grid.com:4444/wd/hub
test_login (tests.holmium_test.HolmiumTests) ... SKIP: unable to initialize driver (name: ie) / or (name: safari )

---

Ran 1 test in 0.004s

OK (SKIP=1)

I can run safari or ie using local browsers, but when trying to run them remotely from our selenium grid there is exact above problem with initialization of the driver.

**Comment by alisaifee** [comment]
Closing since nose support has been dropped as of 1.0.0
