### ISSUE TITLE
assertConditionWithWait is broken (not hugely useful, misleading documentation)

### ISSUE THREAD

**Issue by hyperair** [alisaifee/holmium.core#40]
The docstring for [assertConditionWithWait](https://github.com/alisaifee/holmium.core/blob/master/holmium/core/testcase.py#L135-L150) suggests that `condition` should be an instance of `selenium.webdriver.support.expected_conditions`, but the `WebDriverWait.until` call on line 147 evaluates `condition(element)` only once before execution enters the `until()` method. This suggests that `condition` should really be one of the classes in `expected_conditions`, rather than an instance for the current implementation.

Also, passing in a `WebElement` in `element` is not hugely useful -- most of the conditions in `expected_conditions` expect a locator `(By.something, "locator string")` rather than an element.

I suggest keeping the documentation for `condition` as-is (accepting an instance), dropping the `element` parameter entirely, and just passing `condition` directly to the WebDriverWait: `WebDriverWait(driver, timeout).until(condition)`. Since `WebDriverWait.until` simply accepts a callable that takes a single positional parameter (`driver`), `assertConditionWithWait` becomes a lot more flexible, even allowing lambdas to be used as a `condition`.

**Comment by zehua** [comment]
👍

**Comment by hyperair** [comment]
Additionally, @zehua discovered that `assertConditionWithWait` in its current state does not actually raise the `self.failureException` in the event of an actual failure -- it constructs the exception and that's it:

https://github.com/alisaifee/holmium.core/blob/master/holmium/core/testcase.py#L150

**Comment by alisaifee** [comment]
Released in `0.8.4`
